// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; 
export const LOGIN_FAIL= 'LOGIN_FAIL'; 
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'; 
export const USER_LOADED_FAIL= 'USER_LOADED_FAIL'; 
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'; 
export const AUTHENTICATED_FAIL= 'AUTHENTICATED_FAIL'; 
export const LOGOUT= 'LOGOUT'; 
export const SIGNUP_SUCCESS= 'SIGNUP_SUCCESS'; 
export const SIGNUP_FAIL= 'SIGNUP_FAIL'; 
export const ACTIVATION_SUCCESS= 'ACTIVATION_SUCCESS'; 
export const ACTIVATION_FAIL= 'ACTIVATION_FAIL'; 
export const RESEND_ACTIVATION_SUCCESS= 'RESEND_ACTIVATION_SUCCESS'; 
export const RESEND_ACTIVATION_FAIL= 'RESEND_ACTIVATION_FAIL'; 
export const FORGET_PASSWORD_SUCCESS= 'FORGET_PASSWORD_SUCCESS'; 
export const FORGET_PASSWORD_FAIL= 'FORGET_PASSWORD_FAIL'; 
export const RESET_PASSWORD_SUCCESS= 'RESET_PASSWORD_SUCCESS'; 
export const RESET_PASSWORD_FAIL= 'RESET_PASSWORD_FAIL'; 

// Categories
export const CATEGORY_LOADED_SUCCESS= 'CATEGORY_LOADED_SUCCESS'; 
export const CATEGORY_LOADED_FAIL= 'CATEGORY_LOADED_FAIL'; 
export const CATEGORY_CREATED_SUCCESS= 'CATEGORY_CREATED_SUCCESS'; 
export const CATEGORY_CREATED_FAIL= 'CATEGORY_CREATED_FAIL'; 
export const CATEGORY_REMOVE= 'CATEGORY_REMOVE'; 

// Courses
export const COURSES_LOADED_SUCCESS= 'COURSES_LOADED_SUCCESS'; 
export const COURSES_LOADED_FAIL= 'COURSES_LOADED_FAIL'; 
export const COURSE_USER_SUCCESS= 'COURSE_USER_SUCCESS'; 
export const COURSE_USER_FAIL= 'COURSE_USER_FAIL'; 
export const COURSE_FILTER_SUCCESS= 'COURSE_FILTER_SUCCESS'; 
export const COURSE_FILTER_FAIL= 'COURSE_FILTER_FAIL'; 
export const COURSE_FILTER_ID_SUCCESS= 'COURSE_FILTER_ID_SUCCESS'; 
export const COURSE_FILTER_ID_FAIL= 'COURSE_FILTER_ID_FAIL'; 
export const COURSE_DETAIL_SUCCESS= 'COURSE_DETAIL_SUCCESS'; 
export const COURSE_DETAIL_FAIL= 'COURSE_DETAIL_FAIL';
export const COURSE_DETAIL_REQUEST= 'COURSE_DETAIL_REQUEST';
export const COURSE_DETAIL_RESET= 'COURSE_DETAIL_RESET';
export const COURSE_CREATED_SUCCESS= 'COURSE_CREATED_SUCCESS';
export const COURSE_CREATED_FAIL= 'COURSE_CREATED_FAIL';
export const COURSE_UPDATE_SUCCESS= 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_FAIL= 'COURSE_UPDATE_FAIL';
export const COURSE_REMOVE = 'COURSE_REMOVE';


export const TOPIC_CREATE_SUCCESS= 'TOPIC_CREATE_SUCCESS';
export const TOPIC_CREATE_FAIL= 'TOPIC_CREATE_FAIL';
export const TOPIC_UPDATE_SUCCESS= 'TOPIC_UPDATE_SUCCESS';
export const TOPIC_UPDATE_FAIL= 'TOPIC_UPDATE_FAIL';
export const TOPIC_LOADED_SUCCESS= 'TOPIC_LOADED_SUCCESS';
export const TOPIC_LOADED_FAIL= 'TOPIC_LOADED_FAIL';
export const TOPIC_REMOVE = 'TOPIC_REMOVE';

export const REQUIREMENT_CREATED_SUCCESS= 'REQUIREMENT_CREATED_SUCCESS';
export const REQUIREMENT_CREATED_FAIL= 'REQUIREMENT_CREATED_FAIL';

export const SYLLABUS_CREATED_SUCCESS= 'SYLLABUS_CREATED_SUCCESS';
export const SYLLABUS_CREATED_FAIL= 'SYLLABUS_CREATED_FAIL';
export const SYLLABUS_LIST_LOADED_SUCCESS= 'SYLLABUS_LIST_LOADED_SUCCESS';
export const SYLLABUS_LIST_LOADED_FAIL= 'SYLLABUS_LIST_LOADED_FAIL';
export const SYLLABUS_REMOVE = 'SYLLABUS_REMOVE';


// Account
export const ACCOUNT_DETAIL_REQUEST = 'ACCOUNT_DETAIL_REQUEST';
export const ACCOUNT_DETAIL_SUCCESS = 'ACCOUNT_DETAIL_SUCCESS';
export const ACCOUNT_DETAIL_FAIL = 'ACCOUNT_DETAIL_FAIL';
export const ACCOUNT_COURSE_DETAIL_REQUEST = 'ACCOUNT_COURSE_DETAIL_REQUEST';
export const ACCOUNT_COURSE_DETAIL_SUCCESS = 'ACCOUNT_COURSE_DETAIL_SUCCESS';
export const ACCOUNT_COURSE_DETAIL_FAIL = 'ACCOUNT_COURSE_DETAIL_FAIL';
export const ACCOUNT_UPDATE_REQUEST = 'ACCOUNT_UPDATE_REQUEST';
export const ACCOUNT_UPDATE_SUCCESS = 'ACCOUNT_UPDATE_SUCCESS';
export const ACCOUNT_UPDATE_FAIL = 'ACCOUNT_UPDATE_FAIL';


// search
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

// order
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const LOAD_CART = 'LOAD_CART';
export const CART_START = 'CART_START';
export const CART_SUCCESS = 'CART_SUCCESS';
export const CART_FAIL = 'CART_FAIL';
export const LOAD_ORDER_SUCCESS = 'LOAD_ORDER_SUCCESS';
export const LOAD_ORDER_FAIL = 'LOAD_ORDER_FAIL';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';

// settings
export const SETTINGS_CREATED_SUCCESS = 'SETTINGS_CREATED_SUCCESS'
export const SETTINGS_CREATED_FAIL = 'SETTINGS_CREATED_FAIL'